export const colors = {
  canvas: '#F4F5F7',
  surface: '#FFFFFF',
  surfaceMuted: '#EEF0F3',
  ink: '#24262B',
  muted: '#666B73',
  lineSubtle: '#DDE0E5',
  lineStrong: '#777B83',
  indigo: '#4457A6',
  indigoDeep: '#344383',
  indigoSoft: '#EEF0FA',
  sage: '#718477',
  sageSoft: '#EDF2EE',
  apricot: '#C87D5B',
  apricotSoft: '#FAEFEA',
  error: '#B3261E',
  errorSoft: '#FCEDEA',
  scrim: 'rgba(36,38,43,0.56)',
  focus: '#254FB5',

  // 기존 화면을 primitive 단위로 옮기는 동안 색이 서로 갈라지지 않도록 의미가 같은 별칭만 유지한다.
  paper: '#F4F5F7',
  paperDeep: '#EEF0F3',
  mutedInk: '#666B73',
  faintInk: '#666B73',
  line: '#DDE0E5',
  brand: '#4457A6',
  brandDeep: '#344383',
  brandSoft: '#EEF0FA',
  sky: '#668AA5',
  skySoft: '#EEF3F6',
  acid: '#ECEEFC',
  cobalt: '#4457A6',
  vermilion: '#C87D5B',
  coral: '#C87D5B',
  coralSoft: '#FAE9E1',
  leaf: '#667A62',
  leafSoft: '#E9F0E7',
  blue: '#668AA5',
  blueSoft: '#E7F0F5',
  ochre: '#8B6A42',
  ochreSoft: '#F5EDDF',
  white: '#FFFFFF',
} as const;

export const fonts = {
  display: 'Pretendard_700Bold',
  serif: 'Pretendard_400Regular',
  serifBold: 'Pretendard_700Bold',
  sans: 'Pretendard_400Regular',
  sansMedium: 'Pretendard_600SemiBold',
  sansBold: 'Pretendard_700Bold',
  sansBlack: 'Pretendard_700Bold',
  logoBold: 'Pretendard_700Bold',
} as const;

export const typeScale = {
  profileName: { fontFamily: fonts.sansBold, fontSize: 32, lineHeight: 42, letterSpacing: -0.64 },
  question: { fontFamily: fonts.sansBold, fontSize: 32, lineHeight: 42, letterSpacing: -0.64 },
  screenTitle: { fontFamily: fonts.sansBold, fontSize: 28, lineHeight: 38, letterSpacing: -0.56 },
  sceneAnswer: { fontFamily: fonts.sansBold, fontSize: 24, lineHeight: 36, letterSpacing: -0.48 },
  sectionTitle: { fontFamily: fonts.sansBold, fontSize: 22, lineHeight: 31, letterSpacing: -0.44 },
  body: { fontFamily: fonts.sans, fontSize: 16, lineHeight: 26, letterSpacing: 0 },
  control: { fontFamily: fonts.sansMedium, fontSize: 15, lineHeight: 22, letterSpacing: 0 },
  meta: { fontFamily: fonts.sansMedium, fontSize: 12, lineHeight: 18, letterSpacing: 0 },
} as const;

export const space = {
  xs: 4,
  sm: 8,
  smMd: 12,
  md: 16,
  mdLg: 20,
  lg: 24,
  xl: 32,
  xxl: 40,
  xxxl: 48,
} as const;

export const radii = {
  xs: 8,
  sm: 10,
  md: 14,
  lg: 18,
  xl: 24,
  pill: 999,
} as const;

export const layout = {
  mobileGutter: 20,
  desktopGutter: 20,
  maxContent: 480,
  railWidth: 0,
  minTouch: 44,
  controlHeight: 52,
  optionMinHeight: 60,
  sceneCardMinHeight: 168,
  publicSceneCardMinHeight: 144,
  profileCoverMinHeight: 280,
  statePanelMinHeight: 168,
  bottomTabHeight: 64,
  largeTextScale: 1.5,
  dialogMaxWidth: 390,
} as const;
